apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"meta.helm.sh/release-name":"my-release","meta.helm.sh/release-namespace":"helm","pv.kubernetes.io/bound-by-controller":"yes"},"creationTimestamp":"2024-06-20T15:36:57Z","finalizers":["kubernetes.io/pv-protection"],"labels":{"app":"db","app.kubernetes.io/managed-by":"Helm"},"name":"my-pv","resourceVersion":"166089","uid":"3a5be40d-c995-40d5-8bd5-110759605c99"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"10Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"my-pvc","namespace":"standard","resourceVersion":"166076","uid":"12f75453-af7e-4b42-b6e8-f94c49882518"},"hostPath":{"path":"/mnt/postgres","type":""},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"manuel","volumeMode":"Filesystem"},"status":{"lastPhaseTransitionTime":"2024-06-20T16:17:41Z","phase":"Bound"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-06-20T15:36:57Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2024-06-21T14:31:41Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: db
    app.kubernetes.io/managed-by: Helm
  name: my-pv
  resourceVersion: "232959"
  uid: 3a5be40d-c995-40d5-8bd5-110759605c99
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: my-pvc
    namespace: standard
    resourceVersion: "166076"
    uid: 12f75453-af7e-4b42-b6e8-f94c49882518
  hostPath:
    path: /mnt/postgres
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manuel
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-06-20T16:17:41Z"
  phase: Bound
