apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: kustomize
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
      - name: postgresql
        image: postgres:12.0-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: user
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: db
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: pwd
          - name: POSTGRES_HOST_AUTH_METHOD
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: value
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: pv-storage