apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa
 namespace: standard
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
 minReplicas: 3
 maxReplicas: 6
 targetCPUUtilizationPercentage: 70