apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: UEdBRE1JTl9ERUZBVUxUX0VNQUlMPWFkbWluQGFkbWluLmNvbQpQR0FETUlOX0RFRkFVTFRfUEFT
  PGADMIN_DEFAULT_PASSWORD: U1dPUkQ9cm9vdAo= 
