apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: standard
  labels:
    app: db
spec:
  storageClassName: manuel
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres"